import Head from "next/head";
import Image from "next/image";
import Section1 from "../components/section/Section1";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <>
      <Head>
        <title>형사전문변호사 - 법무법인 대륜</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Section1 />
    </>
  );
}
